### PR TITLE
fixing the breaking modals

### PR DESCRIPTION
**Pull request by sprinklepancake**

### CODE REVIEW

**Review by mcfarhat — CHANGES_REQUESTED** [review]
hey @sprinklepancake , you need to keep the modal-dialog class otherwise the modal will not close.
Also it's best if you actually make (or use an existing) component for this modal, instead of coding it into the wallet directly. You could for example use the NotifyModal component and pass it some arguments, or just build a component for the token swap modal.
Please adjust, review, test and submit with changes.

**Comment by sprinklepancake** [comment]
hey @mcfarhat , i did the changes and made a new component file and gave the modal the specified class.

**Comment by sprinklepancake** [comment]
@mcfarhat the latest commit is regarding the single post style issue, i realized that in the activity page it was unchanged so i fixed it.

**Review by mcfarhat — APPROVED** [review]

**Comment by mcfarhat** [comment]
refactor modal code as component + fix single post activity view

**Pull request merged**
